// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyjhueomtreblgeuxggw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5amh1ZW9tdHJlYmxnZXV4Z2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0OTU0MzIsImV4cCI6MjA5MDA3MTQzMn0.udwI__xfUF2RIkpp3NSr-pMsl7cwhQWgWc5dWXc0CF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});